---

- name: Install packages that allow apt to be used over HTTPS
  apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  vars:
      packages:
          - ca-certificates
          - apt-transport-https
          - curl
          - gnupg

- name: Add an apt signing key for Helm
  apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present

- name: Add Helm Repository
  apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present

- name: Install Helm
  apt:
      name: helm
      state: present
      update_cache: yes